[application]
name = "Byos Queuer"

[bundle]
identifier = "ac.uk.mesnage-lab"
publisher = "Brooks Rady"
short_description = "A GUI for queuing Byos workflows"
long_description = "A simple GUI for queuing Byos workflows and running them in parallel"
icon = ["assets/favicon.ico"]
