// NOTE: The `PartialEq` derive is hidden inside of the code generated by `#[component]`, and I have no need for a full
// `Eq` implementation. Additionally, because the code that needs this `#[expect(...)]` is hidden in that macro, this
// lint needs to be disabled on a module level!
#![expect(clippy::derive_partial_eq_without_eq)]

use dioxus::prelude::*;

use crate::components::delete::Delete;

#[component]
pub fn Job(index: usize, name: String) -> Element {
    rsx! {
        li {
            class: "list-row",
            div {
                class: "font-mono list-col-grow",
                { name }
            }
            Delete { index }
        }
    }
}
